name: praticeing github actions

on:
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=my-org
            -Dsonar.projectKey=github-actions-sonarqube-demo
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        # as my password contain some spical character i am using this
        # u can use docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/springboot-sonarqube .

      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/springboot-sonarqube:latest
  
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from docker hub
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/springboot-sonarqube:latest

      - name: Delete old container
        run: sudo docker rm -f springboot-sonarqube-container

      - name: Run docker container
        run: |
          sudo docker run -d \
          -p 8080:8080 \
          -e JDBC_URL="${{ secrets.APP_NAME }}" \
          --name springboot-sonarqube-container \
          ${{ secrets.DOCKERHUB_USERNAME }}/springboot-sonarqube